name: CMake Build CI

permissions:
  contents: read

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  # ==========================================
  # BUILD ON WINDOWS
  # ==========================================
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Baixar o código do repositório
        uses: actions/checkout@v4

      - name: Configurar o CMake (Windows)
        run: cmake -B build

      - name: Compilar a Engine (Windows Release)
        run: cmake --build build --config Release
